// GENERATED by tools/changelog_to_news.mjs from CHANGELOG.md. Do not edit.
export const NEWS_VERSION = "0.2.0";
export const NEWS_DATE = "2026-10-02";
export const NEWS_ENTRIES: readonly string[] = [
  "Every character has an attack that costs nothing.",
  "The braziers burn.",
  "Skills unlock as you level and get stronger on their own kills.",
];
