// GENERATED by tools/changelog_to_news.mjs from CHANGELOG.md. Do not edit.
export const NEWS_VERSION = "0.1.0";
export const NEWS_DATE = "2026-07-30";
export const NEWS_ENTRIES: readonly string[] = [
  "Bodies fall over when they die: Havok drives a ragdoll off the character and creature skeletons, and corpses lie where they land for six seconds.",
  "A monster shows the hit it just took, and a bolt leaves the casting hand rather than the middle of the chest.",
  "Sound has distance and a room: a far cue is quieter and duller, and how much it rings is the biome's, so a Vaal hall answers and open sand does not.",
];
