/**
 * Turn the top released section of CHANGELOG.md into the menu's LATEST panel.
 *
 * One source for two audiences: the file is what a developer reads on GitHub,
 * and the generated module is what a player reads before pressing PLAY. Copying
 * between them by hand is how a menu ends up advertising a build from a month
 * ago, so it is generated and `news.test.ts` fails if the two have drifted.
 *
 *   node tools/changelog_to_news.mjs
 *
 * Deliberately not a Vite plugin or a build step: everything else generated in
 * this repo (textures, the wardrobe, the tilesets) is a tool you run when you
 * change its input, and the changelog changes once a release.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHANGELOG = join(root, "CHANGELOG.md");
const OUT = join(root, "apps", "web", "src", "news.generated.ts");

/** How many lines of the section the menu has room for. */
const HEADLINE_MAX = 3;

export function parseChangelog(text) {
  const lines = text.split(/\r?\n/);
  let version = null;
  let date = null;
  const entries = [];
  for (const line of lines) {
    const head = /^## \[([^\]]+)\](?:\s*-\s*(\S+))?/.exec(line);
    if (head) {
      // Unreleased is not news: it is work that has not reached the player.
      if (head[1].toLowerCase() === "unreleased") continue;
      if (version) break; // only the newest released section
      version = head[1];
      date = head[2] ?? "";
      continue;
    }
    if (!version) continue;
    const item = /^- (.+)$/.exec(line);
    if (item) entries.push(item[1].trim());
    else if (entries.length && /^\s+\S/.test(line)) {
      // A wrapped bullet: the changelog is hard-wrapped, the menu is not.
      entries[entries.length - 1] += ` ${line.trim()}`;
    }
  }
  return { version, date, entries: entries.slice(0, HEADLINE_MAX) };
}

export function render({ version, date, entries }) {
  const lines = entries.map((e) => `  ${JSON.stringify(e)},`).join("\n");
  return `// GENERATED by tools/changelog_to_news.mjs from CHANGELOG.md. Do not edit.
export const NEWS_VERSION = ${JSON.stringify(version)};
export const NEWS_DATE = ${JSON.stringify(date)};
export const NEWS_ENTRIES: readonly string[] = [
${lines}
];
`;
}

if (process.argv[1] && process.argv[1].endsWith("changelog_to_news.mjs")) {
  const parsed = parseChangelog(readFileSync(CHANGELOG, "utf8"));
  if (!parsed.version) {
    console.error("no released section in CHANGELOG.md");
    process.exit(1);
  }
  writeFileSync(OUT, render(parsed), "utf8");
  console.log(`${parsed.version} (${parsed.date}) -> ${parsed.entries.length} lines`);
}
